### ISSUE TITLE
Cannot find module 'critical'

### ISSUE THREAD

**Issue by johngerome** [johngerome/craftkit#5]
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'critical'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/gerome/www/wyndimar-landing-page/gulpfile.js:14:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by johngerome** [comment]
resolve here 255fd8ab20b26431cd23a68436f2f2fb6c910866
